global using System;
global using System.Net.Http.Json;
global using AgendaMAUI.Models;
global using AgendaMAUI.Services;
global using AgendaMAUI.ViewModels;
global using System.Collections.ObjectModel;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Diagnostics;